"""create user model

Revision ID: b5d2b4a68063
Revises: 
Create Date: 2024-06-30 03:55:43.404337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d2b4a68063'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Hospital_Part',
    sa.Column('part', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('part', 'id'),
    sa.UniqueConstraint('part')
    )
    op.create_index(op.f('ix_Hospital_Part_id'), 'Hospital_Part', ['id'], unique=True)
    op.create_table('dr',
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('family', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('part', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['part'], ['Hospital_Part.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dr_id'), 'dr', ['id'], unique=True)
    op.create_table('employee',
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('family', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('part', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['part'], ['Hospital_Part.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_id'), 'employee', ['id'], unique=True)
    op.create_table('nurse',
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('family', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['Hospital_Part.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nurse_id'), 'nurse', ['id'], unique=True)
    op.create_table('patient',
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('family', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('DateTime', sa.DateTime(), nullable=True),
    sa.Column('dr', sa.Integer(), nullable=True),
    sa.Column('employee', sa.Integer(), nullable=True),
    sa.Column('Nurse', sa.Integer(), nullable=True),
    sa.Column('National_Code', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Nurse'], ['nurse.id'], ),
    sa.ForeignKeyConstraint(['dr'], ['dr.id'], ),
    sa.ForeignKeyConstraint(['employee'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['Hospital_Part.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('National_Code')
    )
    op.create_index(op.f('ix_patient_id'), 'patient', ['id'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=100), nullable=True),
    sa.Column('image_url_type', sa.String(length=100), nullable=True),
    sa.Column('caption', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_id'), 'post', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_id'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_patient_id'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_nurse_id'), table_name='nurse')
    op.drop_table('nurse')
    op.drop_index(op.f('ix_employee_id'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_dr_id'), table_name='dr')
    op.drop_table('dr')
    op.drop_index(op.f('ix_Hospital_Part_id'), table_name='Hospital_Part')
    op.drop_table('Hospital_Part')
    # ### end Alembic commands ###
